PiquageBillsBundle:
    resource: "@PiquageBillsBundle/Controller/"
    type:     annotation
    prefix:   /api/bills

bills:
    type:     rest
    resource: Piquage\BillsBundle\Controller\BillsRestController
# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
