<?php

namespace Piquage\BillsBundle\Repository;

use Piquage\BillsBundle\Entity\Bill;
use Doctrine\ORM\EntityRepository;

/**
 * BillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BillRepository extends EntityRepository {


    
    public function findAllByMonth($month){
        $logger = new \Monolog\Logger("BillRepo");
        $logger->debug('hello?');
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->add('select','b')
                ->add('from', 'PiquageBillsBundle:Bill b')
                ->add('where', $qb->expr()->like('b.due', ':biller'))
                ->add('orderBy', 'b.due DESC');
        $qb->setParameter('biller', $month);
        $logger->debug("hello logger");
        
        return $qb->getQuery()->getResult();
    }
}